CREATE TABLE CATEGORIA_PROD
  (
    ID_CATEGORIA                 numeric (6) NOT NULL ,
    NOMBRE                       Varchar (500) NOT NULL ,
    TIPO_NEGOCIO_ID_TIPO_NEGOCIO numeric (2) NOT NULL
  ) ;
ALTER TABLE CATEGORIA_PROD ADD CONSTRAINT CATEGORIA_PROD_PK PRIMARY KEY ( ID_CATEGORIA ) ;


CREATE TABLE ESTADO
  (
    ID_ESTADO                  numeric (2) NOT NULL ,
    NOMBRE                     Varchar (50) NOT NULL ,
    DESCRIPCION                Varchar (50) NOT NULL ,
    TIPO_ESTADO_ID_TIPO_ESTADO numeric (3) NOT NULL
  ) ;
ALTER TABLE ESTADO ADD CONSTRAINT ESTADO_PK PRIMARY KEY ( ID_ESTADO ) ;


CREATE TABLE HORARIO_ATENCION
  (
    ID_HORARIO         numeric (6) NOT NULL ,
    DIA                Varchar (10) NOT NULL ,
    FECHA_INICIO       Varchar (10) NOT NULL ,
    FECHA_FIN          Varchar (10) NOT NULL ,
    NEGOCIO_ID_NEGOCIO numeric (6) NOT NULL
  ) ;
ALTER TABLE HORARIO_ATENCION ADD CONSTRAINT HORARIO_ATENCION_PK PRIMARY KEY ( ID_HORARIO ) ;


CREATE TABLE IMAGEN
  (
    ID_IMAGEN numeric (7) NOT NULL ,
    IMAGEN bytea NOT NULL ,
    NEGOCIO_ID_NEGOCIO numeric (6) NOT NULL
  ) ;
ALTER TABLE IMAGEN ADD CONSTRAINT IMAGEN_PK PRIMARY KEY ( ID_IMAGEN ) ;


CREATE TABLE NEGOCIO
  (
    ID_NEGOCIO                   numeric (6) NOT NULL ,
    RAZON_SOCIAL                 Varchar (500) NOT NULL ,
    DIRECCION                    Varchar (500) NOT NULL ,
    TELEFONO                     Varchar (500) NOT NULL ,
    SITIO_WEB                    Varchar (500) ,
    CORREO                       Varchar (500) NOT NULL ,
    DESCRIPCION                  Varchar (500) NOT NULL ,
    USUARIO_ID_USUARIO           numeric (6) NOT NULL ,
    TIPO_NEGOCIO_ID_TIPO_NEGOCIO numeric (2) NOT NULL ,
    SOLICITUD_REG_ID_SOLICITUD   numeric (6) ,
    ESTADO_ID_ESTADO             numeric (2) NOT NULL ,
    IMG_PRINCIPAL bytea 
  ) ;
CREATE UNIQUE INDEX NEGOCIO__IDX ON NEGOCIO
  (
    USUARIO_ID_USUARIO ASC
  )
  ;
CREATE UNIQUE INDEX NEGOCIO__IDXv1 ON NEGOCIO
  (
    SOLICITUD_REG_ID_SOLICITUD ASC
  )
  ;
ALTER TABLE NEGOCIO ADD CONSTRAINT NEGOCIO_PK PRIMARY KEY ( ID_NEGOCIO ) ;


CREATE TABLE NEGOCIO_REGISTRADO
  (
    ID_NEGOCIO_REGIST numeric (7) NOT NULL,
    RAZON_SOCIAL      Varchar (50) NOT NULL,
    DIRECCION         Varchar (50) NOT NULL,
    DOC_REPR          Varchar (50) NOT NULL,
    NOMBRE_REPR       Varchar (50) NOT NULL 
  );
ALTER TABLE NEGOCIO_REGISTRADO ADD CONSTRAINT NEGOCIO_REGISTRADO_PK PRIMARY KEY ( ID_NEGOCIO_REGIST ) ;


CREATE TABLE NOTIFICACION
  (
    ID_NOTIFICACION numeric (7) NOT NULL ,
    NOMBRE          Varchar (50) NOT NULL ,
    DESCRIPCION     Varchar (500) NOT NULL ,
    IMAGEN bytea NOT NULL ,
    FECHA_CREACION              DATE NOT NULL ,
    FECHA_TERMINACION           DATE NOT NULL ,
    NEGOCIO_ID_NEGOCIO          numeric (6) NOT NULL ,
    CATEGORIA_PROD_ID_CATEGORIA numeric (6) NOT NULL ,
    TIPO_NOT_ID_TIPO_NOT        numeric (2) NOT NULL
  ) ;
ALTER TABLE NOTIFICACION ADD CONSTRAINT NOTIFICACION_PK PRIMARY KEY ( ID_NOTIFICACION ) ;


CREATE TABLE OFERTA
  (
    ID_OFERTA                   numeric (6) NOT NULL ,
    DESCRIPCION                 Varchar (500) NOT NULL ,
    CATEGORIA_PROD_ID_CATEGORIA numeric (6) NOT NULL ,
    NEGOCIO_ID_NEGOCIO          numeric (6) NOT NULL
  ) ;
ALTER TABLE OFERTA ADD CONSTRAINT OFERTA_PK PRIMARY KEY ( ID_OFERTA ) ;


CREATE TABLE PARAMETRO_SISTEMA
  (
    ID_PARAMETRO numeric (2) NOT NULL ,
    NOMBRE       Varchar (50) NOT NULL ,
    VALOR        Varchar (500) NOT NULL
  ) ;
ALTER TABLE PARAMETRO_SISTEMA ADD CONSTRAINT PARAMETRO_SISTEMA_PK PRIMARY KEY ( ID_PARAMETRO ) ;


CREATE TABLE SOLICITUD_REG
  (
    ID_SOLICITUD       numeric (6) NOT NULL ,
    DESCRIPCION        Varchar (500) NOT NULL ,
    FECHA_CREACION     DATE NOT NULL ,
    FECHA_ATENCION     DATE ,
    RESPUESTA          Varchar (500) ,
    NEGOCIO_ID_NEGOCIO numeric (6) NOT NULL ,
    ESTADO_ID_ESTADO   numeric (2) NOT NULL
  ) ;
CREATE UNIQUE INDEX SOLICITUD_REGISTRO__IDX ON SOLICITUD_REG
  (
    NEGOCIO_ID_NEGOCIO ASC
  )
  ;
ALTER TABLE SOLICITUD_REG ADD CONSTRAINT SOLICITUD_REG_PK PRIMARY KEY ( ID_SOLICITUD ) ;


CREATE TABLE TIPO_ESTADO
  (
    ID_TIPO_ESTADO numeric (3) NOT NULL ,
    NOMBRE         Varchar (50) NOT NULL ,
    DESCRIPCION    Varchar (50) NOT NULL
  ) ;
ALTER TABLE TIPO_ESTADO ADD CONSTRAINT TIPO_ESTADO_PK PRIMARY KEY ( ID_TIPO_ESTADO ) ;


CREATE TABLE TIPO_NEGOCIO
  (
    ID_TIPO_NEGOCIO numeric (2) NOT NULL ,
    NOMBRE          Varchar (50) NOT NULL
  ) ;
ALTER TABLE TIPO_NEGOCIO ADD CONSTRAINT TIPO_NEGOCIO_PK PRIMARY KEY ( ID_TIPO_NEGOCIO ) ;


CREATE TABLE TIPO_NOT
  (
    ID_TIPO_NOT numeric (2) NOT NULL ,
    NOMBRE      Varchar (50) NOT NULL ,
    DESCRIPCION Varchar (100) NOT NULL
  ) ;
ALTER TABLE TIPO_NOT ADD CONSTRAINT TIPO_NOT_PK PRIMARY KEY ( ID_TIPO_NOT ) ;


CREATE TABLE USUARIO
  (
    ID_USUARIO       numeric (6) NOT NULL ,
    NOMBRE           Varchar (50) NOT NULL ,
    IDENTIFICACION   Varchar (50) NOT NULL ,
    TELEFONO         Varchar (50) NOT NULL ,
    DIRECCION        Varchar (50) NOT NULL ,
    CORREO           Varchar (50) NOT NULL ,
    PASSWORD         Varchar (50) NOT NULL ,
    ESTADO_ID_ESTADO numeric (2) NOT NULL
  ) ;
ALTER TABLE USUARIO ADD CONSTRAINT USUARIO_PK PRIMARY KEY ( ID_USUARIO ) ;


ALTER TABLE CATEGORIA_PROD ADD CONSTRAINT CATEGORIA_PROD_TIPO_NEGOCIO_FK FOREIGN KEY ( TIPO_NEGOCIO_ID_TIPO_NEGOCIO ) REFERENCES TIPO_NEGOCIO ( ID_TIPO_NEGOCIO ) ;

ALTER TABLE ESTADO ADD CONSTRAINT ESTADO_TIPO_ESTADO_FK FOREIGN KEY ( TIPO_ESTADO_ID_TIPO_ESTADO ) REFERENCES TIPO_ESTADO ( ID_TIPO_ESTADO ) ;

ALTER TABLE HORARIO_ATENCION ADD CONSTRAINT HORARIO_ATENCION_NEGOCIO_FK FOREIGN KEY ( NEGOCIO_ID_NEGOCIO ) REFERENCES NEGOCIO ( ID_NEGOCIO ) ;

ALTER TABLE IMAGEN ADD CONSTRAINT IMAGEN_NEGOCIO_FK FOREIGN KEY ( NEGOCIO_ID_NEGOCIO ) REFERENCES NEGOCIO ( ID_NEGOCIO ) ;

ALTER TABLE NEGOCIO ADD CONSTRAINT NEGOCIO_ESTADO_FK FOREIGN KEY ( ESTADO_ID_ESTADO ) REFERENCES ESTADO ( ID_ESTADO ) ;

ALTER TABLE NEGOCIO ADD CONSTRAINT NEGOCIO_SOLICITUD_REG_FK FOREIGN KEY ( SOLICITUD_REG_ID_SOLICITUD ) REFERENCES SOLICITUD_REG ( ID_SOLICITUD ) ;

ALTER TABLE NEGOCIO ADD CONSTRAINT NEGOCIO_TIPO_NEGOCIO_FK FOREIGN KEY ( TIPO_NEGOCIO_ID_TIPO_NEGOCIO ) REFERENCES TIPO_NEGOCIO ( ID_TIPO_NEGOCIO ) ;

ALTER TABLE NEGOCIO ADD CONSTRAINT NEGOCIO_USUARIO_FK FOREIGN KEY ( USUARIO_ID_USUARIO ) REFERENCES USUARIO ( ID_USUARIO ) ;

ALTER TABLE NOTIFICACION ADD CONSTRAINT NOTIFICACION_CATEGORIA_PROD_FK FOREIGN KEY ( CATEGORIA_PROD_ID_CATEGORIA ) REFERENCES CATEGORIA_PROD ( ID_CATEGORIA ) ;

ALTER TABLE NOTIFICACION ADD CONSTRAINT NOTIFICACION_NEGOCIO_FK FOREIGN KEY ( NEGOCIO_ID_NEGOCIO ) REFERENCES NEGOCIO ( ID_NEGOCIO ) ;

ALTER TABLE NOTIFICACION ADD CONSTRAINT NOTIFICACION_TIPO_NOT_FK FOREIGN KEY ( TIPO_NOT_ID_TIPO_NOT ) REFERENCES TIPO_NOT ( ID_TIPO_NOT ) ;

ALTER TABLE OFERTA ADD CONSTRAINT OFERTA_CATEGORIA_PROD_FK FOREIGN KEY ( CATEGORIA_PROD_ID_CATEGORIA ) REFERENCES CATEGORIA_PROD ( ID_CATEGORIA ) ;

ALTER TABLE OFERTA ADD CONSTRAINT OFERTA_NEGOCIO_FK FOREIGN KEY ( NEGOCIO_ID_NEGOCIO ) REFERENCES NEGOCIO ( ID_NEGOCIO ) ;

ALTER TABLE SOLICITUD_REG ADD CONSTRAINT SOLICITUD_REG_ESTADO_FK FOREIGN KEY ( ESTADO_ID_ESTADO ) REFERENCES ESTADO ( ID_ESTADO ) ;

ALTER TABLE SOLICITUD_REG ADD CONSTRAINT SOLICITUD_REG_NEGOCIO_FK FOREIGN KEY ( NEGOCIO_ID_NEGOCIO ) REFERENCES NEGOCIO ( ID_NEGOCIO ) ;

ALTER TABLE USUARIO ADD CONSTRAINT USUARIO_ESTADO_FK FOREIGN KEY ( ESTADO_ID_ESTADO ) REFERENCES ESTADO ( ID_ESTADO ) ;
